### ISSUE TITLE
Notifier.IsGetPermission() 始终都是返回 false

### ISSUE THREAD

**Issue by bestK** [rentiansheng/notification#1]
Google Chrome
版本 59.0.3050.3（正式版本） （64 位）

**Comment by rentiansheng** [comment]
什么系统的？ 我去下载一个看看

**Comment by rentiansheng** [comment]
通知权限是基于网站（或者域名），同一个网站下面的页面只需要获取一次权限即可。 如果在域名下已经禁用了。将不会显示通知的，也无法再次获取权限了。 可以同浏览器的菜单查看权限。

设置-》隐私设选下面的 “内容设置”-》通知


还有就是测试的时候要通过http请求来测试，不要直接在浏览打开文件测试
