### ISSUE TITLE
通知中能否使用链接呢

### ISSUE THREAD

**Issue by zuilaoxian** [rentiansheng/notification#2]
尝试在通知中添加链接，无法使用

**Comment by rentiansheng** [comment]
提供下内的参数格式。我试下。

**Comment by zuilaoxian** [comment]
e...like this
`Notifier.Notify('', '通知','<a href="https://github.com/">github</a>');`

**Comment by rentiansheng** [comment]
目前，这个通知组件是支持标准字符串的。不支持html 展示的。 这个其实是可以加onclick 事件， 我目前没有暴露出来。 可以在事件中做相关的操作的

**Comment by zuilaoxian** [comment]
...
