### ISSUE TITLE
可以实现通知时带声音或者弹框震动吗

### ISSUE THREAD

**Issue by shuohao** [rentiansheng/notification#3]

**Comment by rentiansheng** [comment]
目前不支持的。这个应该可以添加， HTML5 中有类似的支持， 
声音这个比较简单，发出通知的时候，直接play 一个声音即可，这个应该也需要权限的。

**Comment by shuohao** [comment]
> 目前不支持的。这个应该可以添加， HTML5 中有类似的支持， 声音这个比较简单，发出通知的时候，直接play 一个声音即可，这个应该也需要权限的。

ok
